### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by danny-waite** [krallistic/kafka-operator#1]
Hey, I came across this whilst browsing for related things on GitHub, looks super cool - nice work.

I'd like to give it a try so I'm wondering A) whats the current state in terms of using in a non-prod environment initially, I note its a WIP and following on from that B) would you like any assistance testing etc.

**Comment by krallistic** [comment]
Thanks a lot.

Yes its work in progress, so absolutely non prod :).

Currently the incluster usage is broken (for faster development i mostly use a quick out of cluster usage), iam gonna fix that in a few days. After that i would be if other people test it. Iam can ping this issue then.

**Comment by danny-waite** [comment]
Thanks for the update, I'll await for your instruction :)

Out of interest, how are you (if you are) dealing with access to Kafka from external sources as well as internal sources? Kafka seems pretty tricky around that with advertised hosts etc.

**Comment by krallistic** [comment]
Fortunately i dont have that problem :) 

But you could look into options like exposing a node port. More pointers/ideas here: https://github.com/Yolean/kubernetes-kafka/issues/13#issuecomment-288775688 

A second option to not use an overlay and use a bridgeip mode with an ip range in your "outside" ip range (but you have other drawbacks in your cluster if you go that approach).
