### ISSUE TITLE
Rebalancing

### ISSUE THREAD

**Issue by krallistic** [krallistic/kafka-operator#6]
Decide how to handle & trigger rebalancing:

1. Do automatic rebalancing
2. Manual rebalancing triggered over a REST interface
3. Manual rebalancing triggered over TPR resource

**Comment by frankdejonge** [comment]
FYI: TPR is deprecated since 1.7: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/

**Comment by krallistic** [comment]
Thanks, i already switched over to CRD a while ago (https://github.com/krallistic/kafka-operator/issues/29) 

Since the isssue is quite outdated, i will probably close this. Currently there is a really basic rebalancing implement. But since Linkedin opensourced CruiseControl i plan to integrate this.

**Comment by krallistic** [comment]
Closing this in favour of #35
